DECLARE @MAX INT

SET @MAX = (SELECT MAX(ID) FROM Aseguradoras)
IF (@MAX IS NULL) SET @MAX = 0
DBCC CHECKIDENT (Aseguradoras, RESEED, @MAX)

SET @MAX = (SELECT MAX(ID) FROM Campos)
IF (@MAX IS NULL) SET @MAX = 0
DBCC CHECKIDENT (Campos, RESEED, @MAX)

SET @MAX = (SELECT MAX(ID) FROM Capturas)
IF (@MAX IS NULL) SET @MAX = 0
DBCC CHECKIDENT (Capturas, RESEED, @MAX)

SET @MAX = (SELECT MAX(ID) FROM Citas)
IF (@MAX IS NULL) SET @MAX = 0
DBCC CHECKIDENT (Citas, RESEED, @MAX)

SET @MAX = (SELECT MAX(ID) FROM Elementos)
IF (@MAX IS NULL) SET @MAX = 0
DBCC CHECKIDENT (Elementos, RESEED, @MAX)

SET @MAX = (SELECT MAX(ID) FROM Estudios)
IF (@MAX IS NULL) SET @MAX = 0
DBCC CHECKIDENT (Estudios, RESEED, @MAX)

SET @MAX = (SELECT MAX(ID) FROM GruposCampos)
IF (@MAX IS NULL) SET @MAX = 0
DBCC CHECKIDENT (GruposCampos, RESEED, @MAX)

SET @MAX = (SELECT MAX(ID) FROM Informes)
IF (@MAX IS NULL) SET @MAX = 0
DBCC CHECKIDENT (Informes, RESEED, @MAX)

SET @MAX = (SELECT MAX(ID) FROM Medicos)
IF (@MAX IS NULL) SET @MAX = 0
DBCC CHECKIDENT (Medicos, RESEED, @MAX)

SET @MAX = (SELECT MAX(ID) FROM Pacientes)
IF (@MAX IS NULL) SET @MAX = 0
DBCC CHECKIDENT (Pacientes, RESEED, @MAX)

SET @MAX = (SELECT MAX(ID) FROM Prestaciones)
IF (@MAX IS NULL) SET @MAX = 0
DBCC CHECKIDENT (Prestaciones, RESEED, @MAX)

SET @MAX = (SELECT MAX(ID) FROM Salas)
IF (@MAX IS NULL) SET @MAX = 0
DBCC CHECKIDENT (Salas, RESEED, @MAX)

SET @MAX = (SELECT MAX(ID) FROM TiposPrestacion)
IF (@MAX IS NULL) SET @MAX = 0
DBCC CHECKIDENT (TiposPrestacion, RESEED, @MAX)
